spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im_platform?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: shASFiendsvng2d2F
  data:
    redis:
      host: 127.0.0.1
      port: 6379

minio:
  endpoint: http://127.0.0.1:26767 #内网地址
  accessKey: MinioAAfd4
  secretKey: MISNGINREyudf34
  bucketName: box-im
  imagePath: image
  filePath: file
  videoPath: video
  domain: http://49.235.111.188:26767

webrtc:
  max-channel: 9 # 多人通话最大通道数量，最大不能超过16,建议值:4,9,16
  iceServers:   #coturn配置
    - urls: stun:www.boxim.online:3478
      username: admin
      credential: UrHHKNvE7nFvBTMV
    - urls: turn:www.boxim.online:3478
      username: admin
      credential: UrHHKNvE7nFvBTMV

