spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 2

websocket:
  enable: true
  port: 8878

tcpsocket:
  enable: false # 暂时不开启
  port: 8879

jwt:
  accessToken:
    secret: MIIBIjANBgkq  # 跟im-platfrom的secret必须一致